### ISSUE TITLE
Error when trying to publish an extension

### ISSUE THREAD

**Issue by tomap** [Microsoft/vsts-extension-build-release-tasks#11]
When trying to publish an extension with your task, I got this error:

```

 ##[debug]exec tool: C:\a\1\s\node_modules\.bin\tfx.cmd
##[debug]Arguments:
##[debug]   extension
##[debug]   publish
##[debug]   --json
##[debug]   --token
##[debug]   ********
##[debug]   --service-url
##[debug]   https://marketplace.visualstudio.com/
##[debug]   --root
##[debug]   C:\a\1\s
##[debug]   --manifest-globs
##[debug]   vss-extensions.json
##[debug]   --loc-root
##[debug]   C:\a\1\s
##[debug]   --overrides-file
##[debug]   C:\Users\BUILDG~1\AppData\Local\Temp\PackageTask-0.753142.tmp
[command]C:\a\1\s\node_modules\.bin\tfx.cmd extension publish --json --token ******** --service-url https://marketplace.visualstudio.com/ --root C:\a\1\s --manifest-globs vss-extensions.json --loc-root C:\a\1\s --overrides-file C:\Users\BUILDG~1\AppData\Local\Temp\PackageTask-0.753142.tmp

C:\a\1\s\node_modules\tfx-cli\_build\lib\qfs.js:39
function fileAccess(path, mode = exports.F_OK) {
                               ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\a\1\s\node_modules\tfx-cli\_build\lib\command.js:3:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
rc:1
success:false
task result: Failed
Processing: ##vso[task.complete result=Failed;]tfx failed with error: Error: C:\a\1\s\node_modules\.bin\tfx.cmd failed with return code: 1
tfx failed with error: Error: C:\a\1\s\node_modules\.bin\tfx.cmd failed with return code: 1
```

It was on a hosted build agent, today.
I tried multiple times

Thank you

**Comment by bfcamara** [comment]
I think it's related to this

https://github.com/Microsoft/tfs-cli/issues/141#issuecomment-245200656

Apparently there is something wrong with the latest version of tfx-cli published a few hours ago.

**Comment by tomap** [comment]
Indeed, this fixes my previous error.
Now, I'm back with an error Ihad yesterday:

```
2016-09-07T12:09:51.8506807Z 
2016-09-07T12:09:51.8506807Z npm WARN enoent ENOENT: no such file or directory, open 'C:\a\1\s\package.json'
2016-09-07T12:09:51.8506807Z npm WARN s No description
2016-09-07T12:09:51.8506807Z npm WARN s No repository field.
2016-09-07T12:09:51.8506807Z npm WARN s No README data
2016-09-07T12:09:51.8506807Z npm WARN s No license field.
2016-09-07T12:09:51.9116807Z [command]C:\a\1\s\node_modules\.bin\tfx.cmd extension publish --json --token ******** --service-url https://marketplace.visualstudio.com/ --root C:\a\1\s --manifest-globs vss-extensions.json --loc-root C:\a\1\s --overrides-file C:\Users\BUILDG~1\AppData\Local\Temp\PackageTask-0.208987.tmp
2016-09-07T12:09:51.9116807Z 
2016-09-07T12:09:51.9116807Z 
2016-09-07T12:10:12.2311178Z Failed Request: Not Found(404) - 
2016-09-07T12:10:12.3071177Z tfx failed with error: Error: C:\a\1\s\node_modules\.bin\tfx.cmd failed with return code: 4294967295
2016-09-07T12:10:12.3161182Z ##[section]Finishing: Publish Extension
```

My extension worked, until I added a new build task that added a lot of weight.
This might be the cause?
the VSIX is now 65 Mb. 
Maybe there is a limit per extension ? I could not find this information in the documentation

**Comment by tomap** [comment]
Yes, I just confirmed that by trying to upload the extension using the web interface:
Maximum size is 20 Mb

Maybe you could display another message ? (in the response body of the server, there myght be a better one ?)

I'm closing this ticket

Thank you
